<?php
namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class CalculatorService extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'Calculator'; // TODO: Change the autogenerated stub
    }
}
