<?php
//namespace App\Facades;
//
//use Illuminate\Support\Facades\Facade;
//
//class MultiplyService extends Facade
//{
//    protected static function getFacadeAccessor()
//    {
//        return 'Multiply'; // TODO: Change the autogenerated stub
//    }
//}
